---
- name: UFW - Allow SSH connections
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Allow HTTP connections
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: UFW - Allow HTTPS connections
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: UFW - Enable UFW and deny-all by default
  community.general.ufw:
    state: enabled
    default: deny